#Collage Search app config options.

options:
  MIN_WORD_COUNT: 10
  DICT_PATH: '/usr/share/dict/words'

flickr:
  API_KEY: '2ee12fb262a51e63f4e3c04f092bec55'
  API_SECRET: '6002a6a1481c6fe0'
  API_URL: 'https://api.flickr.com/services/rest/?'
  API_FORMAT: 'json'
  API_METHOD: 'flickr.photos.search'
  API_SORT: 'relevance'
  TEMP_DIR: '/tmp/collage'

imagemagick:
  ROWS: 2
  COLUMNS: 5
  BG_COLOR: 'white'
  BORDR_SIZE: '+5+5'
  IMG_SIZE: 1000
  
